Do not "Assembler Style" = "Intel" in LPK, it breaks compilation on Linux/Arm (like Raspberry Pi)
Before this change, lazbuild fails to compile the
VampyreImagingPackage.lpk on Raspberry Pi, with error:

```
Error: (11006) Illegal parameter: -Rintel
```

Tested with FPC 3.2.2 and Lazarus 2.2.0.

This setting in LPK seems to be not necessary at all -- without it,
compilation goes OK at least on Linux/Arm (Raspberry Pi) and
Linux/x86_64 (Ubuntu on regular desktop).